/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillHistoryRouteImport } from './routes/bill-history'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as BillingStationsRouteImport } from './routes/billing-stations'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OrderStatusRouteImport } from './routes/order-status'
import { Route as QuickOrderRouteImport } from './routes/quick-order'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as SectionsRouteImport } from './routes/sections'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TableServiceRouteImport } from './routes/table-service'
import { Route as TablesRouteImport } from './routes/tables'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillHistoryRoute = BillHistoryRouteImport.update({
  id: '/bill-history',
  path: '/bill-history',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingStationsRoute = BillingStationsRouteImport.update({
  id: '/billing-stations',
  path: '/billing-stations',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusRoute = OrderStatusRouteImport.update({
  id: '/order-status',
  path: '/order-status',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickOrderRoute = QuickOrderRouteImport.update({
  id: '/quick-order',
  path: '/quick-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionsRoute = SectionsRouteImport.update({
  id: '/sections',
  path: '/sections',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TableServiceRoute = TableServiceRouteImport.update({
  id: '/table-service',
  path: '/table-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bill-history': typeof BillHistoryRoute
  '/billing': typeof BillingRoute
  '/billing-stations': typeof BillingStationsRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/order-status': typeof OrderStatusRoute
  '/quick-order': typeof QuickOrderRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sections': typeof SectionsRoute
  '/staff': typeof StaffRoute
  '/table-service': typeof TableServiceRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bill-history': typeof BillHistoryRoute
  '/billing': typeof BillingRoute
  '/billing-stations': typeof BillingStationsRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/order-status': typeof OrderStatusRoute
  '/quick-order': typeof QuickOrderRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sections': typeof SectionsRoute
  '/staff': typeof StaffRoute
  '/table-service': typeof TableServiceRoute
  '/tables': typeof TablesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bill-history': typeof BillHistoryRoute
  '/billing': typeof BillingRoute
  '/billing-stations': typeof BillingStationsRoute
  '/delivery': typeof DeliveryRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/order-status': typeof OrderStatusRoute
  '/quick-order': typeof QuickOrderRoute
  '/reports': typeof ReportsRoute
  '/reservations': typeof ReservationsRoute
  '/sections': typeof SectionsRoute
  '/staff': typeof StaffRoute
  '/table-service': typeof TableServiceRoute
  '/tables': typeof TablesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bill-history'
    | '/billing'
    | '/billing-stations'
    | '/delivery'
    | '/kitchen'
    | '/menu'
    | '/order-status'
    | '/quick-order'
    | '/reports'
    | '/reservations'
    | '/sections'
    | '/staff'
    | '/table-service'
    | '/tables'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bill-history'
    | '/billing'
    | '/billing-stations'
    | '/delivery'
    | '/kitchen'
    | '/menu'
    | '/order-status'
    | '/quick-order'
    | '/reports'
    | '/reservations'
    | '/sections'
    | '/staff'
    | '/table-service'
    | '/tables'
  id:
    | '__root__'
    | '/'
    | '/bill-history'
    | '/billing'
    | '/billing-stations'
    | '/delivery'
    | '/kitchen'
    | '/menu'
    | '/order-status'
    | '/quick-order'
    | '/reports'
    | '/reservations'
    | '/sections'
    | '/staff'
    | '/table-service'
    | '/tables'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillHistoryRoute: typeof BillHistoryRoute
  BillingRoute: typeof BillingRoute
  BillingStationsRoute: typeof BillingStationsRoute
  DeliveryRoute: typeof DeliveryRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  OrderStatusRoute: typeof OrderStatusRoute
  QuickOrderRoute: typeof QuickOrderRoute
  ReportsRoute: typeof ReportsRoute
  ReservationsRoute: typeof ReservationsRoute
  SectionsRoute: typeof SectionsRoute
  StaffRoute: typeof StaffRoute
  TableServiceRoute: typeof TableServiceRoute
  TablesRoute: typeof TablesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bill-history': {
      id: '/bill-history'
      path: '/bill-history'
      fullPath: '/bill-history'
      preLoaderRoute: typeof BillHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-stations': {
      id: '/billing-stations'
      path: '/billing-stations'
      fullPath: '/billing-stations'
      preLoaderRoute: typeof BillingStationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status': {
      id: '/order-status'
      path: '/order-status'
      fullPath: '/order-status'
      preLoaderRoute: typeof OrderStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-order': {
      id: '/quick-order'
      path: '/quick-order'
      fullPath: '/quick-order'
      preLoaderRoute: typeof QuickOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sections': {
      id: '/sections'
      path: '/sections'
      fullPath: '/sections'
      preLoaderRoute: typeof SectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-service': {
      id: '/table-service'
      path: '/table-service'
      fullPath: '/table-service'
      preLoaderRoute: typeof TableServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillHistoryRoute: BillHistoryRoute,
  BillingRoute: BillingRoute,
  BillingStationsRoute: BillingStationsRoute,
  DeliveryRoute: DeliveryRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  OrderStatusRoute: OrderStatusRoute,
  QuickOrderRoute: QuickOrderRoute,
  ReportsRoute: ReportsRoute,
  ReservationsRoute: ReservationsRoute,
  SectionsRoute: SectionsRoute,
  StaffRoute: StaffRoute,
  TableServiceRoute: TableServiceRoute,
  TablesRoute: TablesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
